"""zenavif_ultraprune picker config v2 — adopts the 2026-05-17 sweep winners (ultraprune-27feat + v14+z_rmse (5-seed ship +9.33 pp)).

Multi-seed verdict: **ship** (n_seeds=5, delta_argmin pp median 9.329446064139942, stdev 7.299097849562209).
Aggregate: benchmarks/ultraprune_zenavif_v14_2026-05-17/aggregate.json


Wraps zenavif_picker_config_ultraprune + overrides FEATURE_TRANSFORMS / FEATURE_TRANSFORM_PARAMS
with the per-feature winners from the feature_transform_sweep.py
recommendation at:

  benchmarks/ultraprune_zenavif_v14_2026-05-17/seed_0xcafe/recommended_transforms.py

Generated by zentrain/tools/promote_recommended_to_config.py.
"""

from __future__ import annotations

from pathlib import Path

from zenavif_picker_config_ultraprune import (  # noqa: F401
    KEEP_FEATURES,
    PARETO,
    FEATURES,
    ZQ_TARGETS,
    CATEGORICAL_AXES,
    SCALAR_AXES,
    SCALAR_SENTINELS,
    SCALAR_DISPLAY_RANGES,
    OUTPUT_SPECS,
    SPARSE_OVERRIDES,
    parse_config_name,
)

OUT_JSON = Path("benchmarks/zenavif_ultraprune_hybrid_v2_2026-05-17.json")
OUT_LOG = Path("benchmarks/zenavif_ultraprune_hybrid_v2_2026-05-17.log")

FEATURE_TRANSFORMS = {
    'feat_uniformity': 'clip_then_log1p',
    'feat_quant_survival_y_p25': 'winsor_then_log',
    'feat_gradient_fraction': 'clip_then_log1p_then_winsor',
    'feat_aq_map_p90': 'winsor_p99',
    'feat_cb_peak_sharpness': 'winsor_then_log',
    'feat_aq_map_p95': 'winsor_p99',
    'feat_grayscale_score': 'winsor_then_log',
    'feat_patch_fraction_fast': 'winsor_then_log',
    'feat_cr_peak_sharpness': 'winsor_p99',
    'feat_luma_histogram_entropy': 'clip_then_log1p',
    'feat_log_aspect_abs': 'clip_then_log1p_then_winsor',
    'feat_dct_compressibility_y': 'clip_then_log1p_then_winsor',
    'feat_flat_color_block_ratio': 'clip_then_log1p',
    'feat_laplacian_variance_p99': 'clip_then_log1p_then_winsor',
    'feat_cb_horiz_sharpness': 'winsor_p99',
    'feat_cb_vert_sharpness': 'winsor_p99',
    'feat_aspect_min_over_max': 'winsor_then_log',
    'feat_min_dim': 'clip_then_log1p_then_winsor',
    'feat_quant_survival_y': 'clip_then_log1p',
    'feat_quant_survival_y_p10': 'signed_sqrt',
    'feat_patch_fraction': 'winsor_then_signed_cbrt',
}

FEATURE_TRANSFORM_PARAMS = {
    'feat_uniformity': [0.577881],
    'feat_quant_survival_y_p25': [0, 0.142857],
    'feat_gradient_fraction': [0.458089, 0, 0.189713],
    'feat_aq_map_p90': [4.52871, 5.0402],
    'feat_cb_peak_sharpness': [0, 5],
    'feat_aq_map_p95': [4.79443, 5.17458],
    'feat_grayscale_score': [0.000626, 0.928085],
    'feat_patch_fraction_fast': [0, 0.043945],
    'feat_cr_peak_sharpness': [2, 15],
    'feat_luma_histogram_entropy': [3.6995],
    'feat_log_aspect_abs': [0.287682, 0, 0.114843],
    'feat_dct_compressibility_y': [20.2593, 0, 3.97418],
    'feat_flat_color_block_ratio': [0.183166],
    'feat_laplacian_variance_p99': [5.04664, 0, 0.363362],
    'feat_cb_horiz_sharpness': [0.001995, 0.02098],
    'feat_cb_vert_sharpness': [0.0020975, 0.0215075],
    'feat_aspect_min_over_max': [0.75, 1],
    'feat_min_dim': [5.54518, 0, 0.771453],
    'feat_quant_survival_y': [0.092246],
    'feat_patch_fraction': [0, 0.011719],
}
