"""zenavif picker config v2 — RETRACTED 2026-05-17. Do NOT bake into production.

WARNING: 3-seed multi_seed_confirm.py verdict on these transforms is
**noise** (median Δ argmin +1.65 pp, stdev 5.48 pp, range
-1.14..+9.43; Δ mean overhead -1.20 pp). See
`benchmarks/multiseed_zenavif_v14_2026-05-17/aggregate.json`.

The original single-seed sweep --confirm result of +2.57 pp was within
seed-to-seed variance. This file is kept only as a reproducibility
artifact — to bake a production zenavif picker, use
`zenavif_picker_config` (no transform overrides) until a future sweep
produces multi-seed-locked winners.

Note: zenavif's val set is small (218 rows) relative to its config
space (200 configs), giving ≈1.1 rows/config. This data-to-search-
space ratio means seed-to-seed variance dominates any small transform
effect; future sweeps will likely also fall in the noise regime unless
the sweep corpus expands or the config grid is pruned.

----

Original docstring follows below:

zenavif picker config v2 — adopts the 2026-05-17 sweep winners (v14+z_rmse, +2.57 pp argmin).

Wraps zenavif_picker_config + overrides FEATURE_TRANSFORMS / FEATURE_TRANSFORM_PARAMS
with the per-feature winners from the feature_transform_sweep.py
recommendation at:

  /home/lilith/work/zen/zenanalyze/benchmarks/feat_xform_zenavif_v14_2026-05-17/recommended_transforms.py

Generated by zentrain/tools/promote_recommended_to_config.py.
"""

from __future__ import annotations

from pathlib import Path

from zenavif_picker_config import (  # noqa: F401
    PARETO,
    FEATURES,
    ZQ_TARGETS,
    CATEGORICAL_AXES,
    SCALAR_AXES,
    SCALAR_SENTINELS,
    SCALAR_DISPLAY_RANGES,
    OUTPUT_SPECS,
    SPARSE_OVERRIDES,
    parse_config_name,
    KEEP_FEATURES,
)

OUT_JSON = Path("benchmarks/zenavif_hybrid_v2_2026-05-17.json")
OUT_LOG = Path("benchmarks/zenavif_hybrid_v2_2026-05-17.log")

FEATURE_TRANSFORMS = {
    'feat_variance_spread': 'clip_then_log1p_then_winsor',
    'feat_uniformity': 'clip_then_log1p',
    'feat_quant_survival_y_p25': 'winsor_then_log',
    'feat_aq_map_std': 'clip_then_log1p',
    'feat_gradient_fraction': 'clip_then_log1p_then_winsor',
    'feat_aq_map_p90': 'winsor_p99',
    'feat_noise_floor_uv': 'winsor_then_log',
    'feat_cb_peak_sharpness': 'winsor_then_log',
    'feat_aq_map_p95': 'winsor_p99',
    'feat_grayscale_score': 'winsor_then_log',
    'feat_noise_floor_y_p75': 'quantile_bins',
    'feat_patch_fraction_fast': 'winsor_then_log',
    'feat_colourfulness': 'winsor_then_log',
    'feat_chroma_complexity': 'winsor_then_log',
    'feat_laplacian_variance_peak': 'quantile_bins',
    'feat_edge_slope_stdev': 'clip_then_log1p_then_winsor',
    'feat_cr_peak_sharpness': 'winsor_p99',
    'feat_luma_histogram_entropy': 'clip_then_log1p',
    'feat_log_aspect_abs': 'clip_then_log1p_then_winsor',
    'feat_noise_floor_uv_p50': 'winsor_then_log',
    'feat_dct_compressibility_y': 'clip_then_log1p_then_winsor',
    'feat_flat_color_block_ratio': 'clip_then_log1p',
    'feat_dct_compressibility_uv': 'clip_then_log1p_then_winsor',
    'feat_laplacian_variance_p99': 'clip_then_log1p_then_winsor',
    'feat_cr_vert_sharpness': 'clip_then_log1p_then_winsor',
    'feat_noise_floor_uv_p25': 'clip_then_log1p_then_winsor',
    'feat_cb_horiz_sharpness': 'winsor_p99',
    'feat_cb_vert_sharpness': 'winsor_p99',
    'feat_aspect_min_over_max': 'winsor_then_log',
    'feat_high_freq_energy_ratio': 'winsor_then_log',
    'feat_noise_floor_y_p50': 'clip_then_log1p',
    'feat_cr_horiz_sharpness': 'winsor_then_log',
    'feat_cb_sharpness': 'clip_then_log1p_then_winsor',
    'feat_luma_kurtosis': 'clip_then_log1p',
    'feat_min_dim': 'clip_then_log1p_then_winsor',
    'feat_quant_survival_y_p50': 'clip_then_log1p',
    'feat_quant_survival_y': 'clip_then_log1p',
    'feat_quant_survival_y_p10': 'signed_sqrt',
    'feat_noise_floor_y': 'signed_sqrt',
    'feat_patch_fraction': 'winsor_then_signed_cbrt',
    'feat_noise_floor_y_p90': 'winsor_then_log',
}

FEATURE_TRANSFORM_PARAMS = {
    'feat_variance_spread': [0.85318, 0, 0.155778],
    'feat_uniformity': [0.577881],
    'feat_quant_survival_y_p25': [0, 0.142857],
    'feat_aq_map_std': [0.807997],
    'feat_gradient_fraction': [0.458089, 0, 0.189713],
    'feat_aq_map_p90': [4.52871, 5.0402],
    'feat_noise_floor_uv': [0, 0.111028],
    'feat_cb_peak_sharpness': [0, 5],
    'feat_aq_map_p95': [4.79443, 5.17458],
    'feat_grayscale_score': [0.000626, 0.928085],
    'feat_noise_floor_y_p75': [0.383199, 0.642753, 0.894707, 1, 1, 1, 1],
    'feat_patch_fraction_fast': [0, 0.043945],
    'feat_colourfulness': [0, 146.992],
    'feat_chroma_complexity': [0, 0.323435],
    'feat_laplacian_variance_peak': [5.54518, 5.54518, 5.54518, 5.54518, 5.54518, 5.54518, 5.54518],
    'feat_edge_slope_stdev': [3.23252, 0, 0.307378],
    'feat_cr_peak_sharpness': [2, 15],
    'feat_luma_histogram_entropy': [3.6995],
    'feat_log_aspect_abs': [0.287682, 0, 0.114843],
    'feat_noise_floor_uv_p50': [0, 0.319658],
    'feat_dct_compressibility_y': [20.2593, 0, 3.97418],
    'feat_flat_color_block_ratio': [0.183166],
    'feat_dct_compressibility_uv': [7.44889, 0, 2.81404],
    'feat_laplacian_variance_p99': [5.04664, 0, 0.363362],
    'feat_cr_vert_sharpness': [0.00965, 0, 0.189802],
    'feat_noise_floor_uv_p25': [0.01486, 0, 0.129668],
    'feat_cb_horiz_sharpness': [0.001995, 0.02098],
    'feat_cb_vert_sharpness': [0.0020975, 0.0215075],
    'feat_aspect_min_over_max': [0.75, 1],
    'feat_high_freq_energy_ratio': [0.121632, 0.278718],
    'feat_noise_floor_y_p50': [0.44129],
    'feat_cr_horiz_sharpness': [0.010295, 0.0782075],
    'feat_cb_sharpness': [0.0043035, 0, 0.0221504],
    'feat_luma_kurtosis': [24.2712],
    'feat_min_dim': [5.54518, 0, 0.771453],
    'feat_quant_survival_y_p50': [0.047619],
    'feat_quant_survival_y': [0.092246],
    'feat_patch_fraction': [0, 0.011719],
    'feat_noise_floor_y_p90': [0.40742, 1],
}
