"""zenavif picker config v3_stable — RETRACTED 2026-05-17. Do NOT bake.

WARNING: 3-seed multi_seed_confirm.py against this config gives a
catastrophic baseline_argmin: median 6.5% vs the original config's
19.2% (Δ -12.7 pp). Despite being the majority-vote across 3 sweep
seeds (= seed-stable), these transforms compound overfit because
zenavif's KEEP_FEATURES = 52 (vs zenwebp's 33). The screen-based
transform sweep requires pre-pruned feature sets to generalize.

See `benchmarks/screen_seed_stability_findings_2026-05-17.md` for the
full diagnosis. Kept only as a reproducibility artifact.

----

Original docstring follows below:

zenavif picker config v2 — adopts the 2026-05-17 sweep winners (seed-stable v14+z_rmse majority vote of 3 seeds).

Wraps zenavif_picker_config + overrides FEATURE_TRANSFORMS / FEATURE_TRANSFORM_PARAMS
with the per-feature winners from the feature_transform_sweep.py
recommendation at:

  benchmarks/seed_stable_zenavif_v14_2026-05-17/recommended_transforms.py

Generated by zentrain/tools/promote_recommended_to_config.py.
"""

from __future__ import annotations

from pathlib import Path

from zenavif_picker_config import (  # noqa: F401
    PARETO,
    FEATURES,
    ZQ_TARGETS,
    CATEGORICAL_AXES,
    SCALAR_AXES,
    SCALAR_SENTINELS,
    SCALAR_DISPLAY_RANGES,
    OUTPUT_SPECS,
    SPARSE_OVERRIDES,
    parse_config_name,
    KEEP_FEATURES,
)

OUT_JSON = Path("benchmarks/zenavif_hybrid_v3_stable_2026-05-17.json")
OUT_LOG = Path("benchmarks/zenavif_hybrid_v3_stable_2026-05-17.log")

FEATURE_TRANSFORMS = {
    'feat_aq_map_p90': 'winsor_p99',
    'feat_aq_map_p95': 'winsor_p99',
    'feat_aq_map_std': 'clip_then_log1p',
    'feat_aspect_min_over_max': 'winsor_then_log',
    'feat_cb_horiz_sharpness': 'winsor_then_signed_cbrt',
    'feat_cb_peak_sharpness': 'winsor_then_log',
    'feat_cb_sharpness': 'clip_then_log1p_then_winsor',
    'feat_cb_vert_sharpness': 'winsor_p99',
    'feat_chroma_complexity': 'winsor_then_log',
    'feat_colourfulness': 'clip_then_log1p_then_winsor',
    'feat_cr_horiz_sharpness': 'winsor_then_log',
    'feat_dct_compressibility_uv': 'winsor_p99',
    'feat_dct_compressibility_y': 'clip_then_log1p_then_winsor',
    'feat_flat_color_block_ratio': 'clip_then_log1p',
    'feat_gradient_fraction': 'clip_then_log1p',
    'feat_grayscale_score': 'winsor_then_log',
    'feat_high_freq_energy_ratio': 'winsor_then_log',
    'feat_laplacian_variance_p99': 'clip_then_log1p_then_winsor',
    'feat_laplacian_variance_peak': 'quantile_bins',
    'feat_log_aspect_abs': 'winsor_then_log',
    'feat_luma_histogram_entropy': 'clip_then_log1p',
    'feat_min_dim': 'clip_then_log1p',
    'feat_noise_floor_uv': 'winsor_then_log',
    'feat_noise_floor_uv_p50': 'winsor_then_log',
    'feat_noise_floor_y_p75': 'winsor_p99',
    'feat_noise_floor_y_p90': 'quantile_bins',
    'feat_patch_fraction_fast': 'winsor_then_log',
    'feat_quant_survival_y': 'clip_then_log1p',
    'feat_quant_survival_y_p25': 'winsor_then_log',
    'feat_uniformity': 'clip_then_log1p_then_winsor',
    'feat_variance_spread': 'clip_then_log1p',
}

FEATURE_TRANSFORM_PARAMS = {
    'feat_aq_map_p90': [4.54425, 5.03537],
    'feat_aq_map_p95': [4.80438, 5.1709],
    'feat_aq_map_std': [0.81211],
    'feat_aspect_min_over_max': [0.75, 1],
    'feat_cb_horiz_sharpness': [0.002495, 0.02136],
    'feat_cb_peak_sharpness': [0, 4],
    'feat_cb_sharpness': [0.00456275, 0, 0.0203448],
    'feat_cb_vert_sharpness': [0.0025925, 0.0215792],
    'feat_chroma_complexity': [0, 0.318672],
    'feat_colourfulness': [30.1589, 0, 4.15606],
    'feat_cr_horiz_sharpness': [0.010425, 0.0865758],
    'feat_dct_compressibility_uv': [3.37852, 15.3357],
    'feat_dct_compressibility_y': [20.3894, 0, 3.94088],
    'feat_flat_color_block_ratio': [0.183451],
    'feat_gradient_fraction': [0.433594],
    'feat_grayscale_score': [0.000216367, 0.976028],
    'feat_high_freq_energy_ratio': [0.1223, 0.277661],
    'feat_laplacian_variance_p99': [5.17248, 0, 0.254598],
    'feat_laplacian_variance_peak': [5.54518, 5.54518, 5.54518, 5.54518, 5.54518, 5.54518, 5.54518],
    'feat_log_aspect_abs': [0, 0.409379],
    'feat_luma_histogram_entropy': [3.69903],
    'feat_min_dim': [5.54518],
    'feat_noise_floor_uv': [0, 0.144945],
    'feat_noise_floor_uv_p50': [0, 0.37163],
    'feat_noise_floor_y_p75': [0.652496, 1],
    'feat_noise_floor_y_p90': [0.995525, 1, 1, 1, 1, 1, 1],
    'feat_patch_fraction_fast': [0, 0.044689],
    'feat_quant_survival_y': [0.0645493],
    'feat_quant_survival_y_p25': [0, 0.153439],
    'feat_uniformity': [0.577543, 0, 0.236515],
    'feat_variance_spread': [0.843616],
}
