"""zenavif picker config pruned — drops 10 features that
the LOO multiseed analysis identified as actively harmful (removing
them improves argmin by ≥0.5 pp with overhead
trade ≤1.00 pp).

Source: benchmarks/loo_zenavif_multiseed_2026-05-03.tsv

Generated by zentrain/tools/build_pruned_config.py.
"""

from __future__ import annotations

from pathlib import Path

from zenavif_picker_config import (  # noqa: F401
    PARETO,
    FEATURES,
    ZQ_TARGETS,
    CATEGORICAL_AXES,
    SCALAR_AXES,
    SCALAR_SENTINELS,
    SCALAR_DISPLAY_RANGES,
    FEATURE_TRANSFORMS,
    OUTPUT_SPECS,
    SPARSE_OVERRIDES,
    parse_config_name,
)
from zenavif_picker_config import KEEP_FEATURES as BASE_KEEP_FEATURES

OUT_JSON = Path("benchmarks/zenavif_hybrid_pruned_2026-05-17.json")
OUT_LOG = Path("benchmarks/zenavif_hybrid_pruned_2026-05-17.log")

# Drop-rationale (from LOO 2026-05-03 multiseed analysis):
#   feat_quant_survival_uv_p10: Δargmin +6.30pp, Δoverhead -0.084pp
#   feat_noise_floor_y_p75: Δargmin +6.02pp, Δoverhead +0.092pp
#   feat_cb_sharpness: Δargmin +5.78pp, Δoverhead -0.030pp
#   feat_noise_floor_uv_p25: Δargmin +5.76pp, Δoverhead +0.042pp
#   feat_noise_floor_y_p50: Δargmin +5.48pp, Δoverhead -0.038pp
#   feat_aq_map_std: Δargmin +5.30pp, Δoverhead +0.054pp
#   feat_noise_floor_y_p25: Δargmin +4.92pp, Δoverhead -0.056pp
#   feat_edge_slope_stdev: Δargmin +4.92pp, Δoverhead -0.050pp
#   feat_cr_sharpness: Δargmin +4.70pp, Δoverhead +0.100pp
#   feat_noise_floor_y: Δargmin +4.56pp, Δoverhead +0.086pp

DROP_FEATURES = [
    'feat_quant_survival_uv_p10',
    'feat_noise_floor_y_p75',
    'feat_cb_sharpness',
    'feat_noise_floor_uv_p25',
    'feat_noise_floor_y_p50',
    'feat_aq_map_std',
    'feat_noise_floor_y_p25',
    'feat_edge_slope_stdev',
    'feat_cr_sharpness',
    'feat_noise_floor_y',
]

KEEP_FEATURES = [f for f in BASE_KEEP_FEATURES if f not in DROP_FEATURES]
