"""zenjpeg picker config v2 — RETRACTED 2026-05-17. Do NOT bake into production.

WARNING: 3-seed multi_seed_confirm.py verdict on these transforms is
**regress** (median Δ argmin -6.81 pp, stdev 1.75 pp, range
-6.86..-3.81; Δ mean overhead +2.17 pp). See
`benchmarks/multiseed_zenjpeg_v14_2026-05-17/aggregate.json`.

The original single-seed sweep --confirm result of +3.74 pp was noise.
This file is kept only as a reproducibility artifact — to bake a
production zenjpeg picker, use `zenjpeg_picker_config` (no transform
overrides) until a future sweep produces multi-seed-locked winners.

----

Original docstring follows below:

zenjpeg picker config v2 — adopts the 2026-05-17 sweep winners (singles+z_rmse, +3.74 pp argmin).

Wraps zenjpeg_picker_config + overrides FEATURE_TRANSFORMS / FEATURE_TRANSFORM_PARAMS
with the per-feature winners from the feature_transform_sweep.py
recommendation at:

  /home/lilith/work/zen/zenanalyze/benchmarks/feat_xform_zenjpeg_singles_zrmse_2026-05-17/recommended_transforms.py

Generated by zentrain/tools/promote_recommended_to_config.py.
"""

from __future__ import annotations

from pathlib import Path

from zenjpeg_picker_config import (  # noqa: F401
    PARETO,
    FEATURES,
    ZQ_TARGETS,
    CATEGORICAL_AXES,
    SCALAR_AXES,
    SCALAR_SENTINELS,
    SCALAR_DISPLAY_RANGES,
    OUTPUT_SPECS,
    SPARSE_OVERRIDES,
    parse_config_name,
    KEEP_FEATURES,
)

OUT_JSON = Path("benchmarks/zenjpeg_hybrid_v2_2026-05-17.json")
OUT_LOG = Path("benchmarks/zenjpeg_hybrid_v2_2026-05-17.log")

FEATURE_TRANSFORMS = {
    'feat_dct_compressibility_uv': 'winsor_p99',
    'feat_gradient_fraction': 'clip_then_log1p',
    'feat_uniformity': 'clip_then_log1p',
    'feat_cr_sharpness': 'winsor_p99',
    'feat_quant_survival_uv': 'winsor_p99',
    'feat_cr_peak_sharpness': 'winsor_p99',
    'feat_aq_map_p75': 'winsor_p99',
    'feat_luma_histogram_entropy': 'clip_then_log1p',
    'feat_cb_sharpness': 'winsor_p99',
    'feat_aq_map_mean': 'clip_then_log1p',
    'feat_cb_horiz_sharpness': 'winsor_p99',
    'feat_grayscale_score': 'quantile_bins',
    'feat_cr_horiz_sharpness': 'quantile_bins',
    'feat_laplacian_variance_p75': 'winsor_p99',
    'feat_laplacian_variance_p90': 'clip_then_log1p',
    'feat_colourfulness': 'clip_then_log1p',
    'feat_noise_floor_uv': 'winsor_p99',
    'feat_flat_color_block_ratio': 'clip_then_log1p',
    'feat_cb_vert_sharpness': 'winsor_p99',
    'feat_variance_spread': 'clip_then_log1p',
    'feat_laplacian_variance_p50': 'clip_then_log1p',
    'feat_dct_compressibility_y': 'quantile_bins',
    'feat_aspect_min_over_max': 'log',
    'feat_edge_slope_stdev': 'log',
    'feat_luma_kurtosis': 'clip_then_log1p',
    'feat_noise_floor_y': 'signed_cbrt',
    'feat_gradient_fraction_smooth': 'clip_then_log1p',
    'feat_aq_map_std': 'clip_then_log1p',
    'feat_noise_floor_y_p50': 'winsor_p99',
    'feat_cr_vert_sharpness': 'winsor_p99',
    'feat_noise_floor_y_p90': 'clip_then_log1p',
    'feat_aq_map_p90': 'winsor_p99',
    'feat_laplacian_variance_p99': 'log',
    'feat_variance': 'log',
    'feat_edge_density': 'signed_cbrt',
    'feat_quant_survival_y': 'quantile_bins',
}

FEATURE_TRANSFORM_PARAMS = {
    'feat_dct_compressibility_uv': [3.09766, 12.124],
    'feat_gradient_fraction': [0.467773],
    'feat_uniformity': [0.598389],
    'feat_cr_sharpness': [0.00362, 0.010193],
    'feat_quant_survival_uv': [0.005673, 0.021531],
    'feat_cr_peak_sharpness': [2, 16],
    'feat_aq_map_p75': [3.00214, 4.8569],
    'feat_luma_histogram_entropy': [3.63765],
    'feat_cb_sharpness': [0.004446, 0.012817],
    'feat_aq_map_mean': [2.67547],
    'feat_cb_horiz_sharpness': [0.00185, 0.01482],
    'feat_grayscale_score': [0.00441, 0.016483, 0.036488, 0.059708, 0.109425, 0.197098, 0.395649],
    'feat_cr_horiz_sharpness': [0.00307, 0.00799, 0.01403, 0.02251, 0.03485, 0.06111, 0.1266],
    'feat_laplacian_variance_p75': [1.09861, 3.78419],
    'feat_laplacian_variance_p90': [1.79176],
    'feat_colourfulness': [10.7241],
    'feat_noise_floor_uv': [0, 0.060149],
    'feat_flat_color_block_ratio': [0.194092],
    'feat_cb_vert_sharpness': [0.00206, 0.0146],
    'feat_variance_spread': [0.889506],
    'feat_laplacian_variance_p50': [0.693147],
    'feat_dct_compressibility_y': [6.65527, 10.8566, 14.2832, 17.6318, 21.2656, 26.6075, 34.541],
    'feat_luma_kurtosis': [3.54519],
    'feat_gradient_fraction_smooth': [0.834367],
    'feat_aq_map_std': [1.31026],
    'feat_noise_floor_y_p50': [0.137614, 0.677118],
    'feat_cr_vert_sharpness': [0.00815, 0.06162],
    'feat_noise_floor_y_p90': [0.472643],
    'feat_aq_map_p90': [3.66071, 5.29777],
    'feat_quant_survival_y': [0.029695, 0.049619, 0.061988, 0.074234, 0.089828, 0.111034, 0.144593],
}
