"""zenjpeg picker config pruned — drops 17 features that
the LOO multiseed analysis identified as actively harmful (removing
them improves argmin by ≥0.5 pp with overhead
trade ≤0.50 pp).

Source: benchmarks/loo_zenjpeg_multiseed_2026-05-17.tsv

Generated by zentrain/tools/build_pruned_config.py.
"""

from __future__ import annotations

from pathlib import Path

from zenjpeg_picker_config import (  # noqa: F401
    PARETO,
    FEATURES,
    ZQ_TARGETS,
    CATEGORICAL_AXES,
    SCALAR_AXES,
    SCALAR_SENTINELS,
    SCALAR_DISPLAY_RANGES,
    FEATURE_TRANSFORMS,
    OUTPUT_SPECS,
    SPARSE_OVERRIDES,
    parse_config_name,
)
from zenjpeg_picker_config import KEEP_FEATURES as BASE_KEEP_FEATURES

OUT_JSON = Path("benchmarks/zenjpeg_hybrid_pruned_2026-05-17.json")
OUT_LOG = Path("benchmarks/zenjpeg_hybrid_pruned_2026-05-17.log")

# Drop-rationale (from LOO 2026-05-03 multiseed analysis):
#   feat_cr_horiz_sharpness: Δargmin +4.66pp, Δoverhead -0.338pp
#   feat_laplacian_variance: Δargmin +4.40pp, Δoverhead -0.326pp
#   feat_cb_vert_sharpness: Δargmin +3.88pp, Δoverhead -0.148pp
#   feat_cb_peak_sharpness: Δargmin +2.98pp, Δoverhead -0.134pp
#   feat_edge_density: Δargmin +2.62pp, Δoverhead -0.066pp
#   feat_variance_spread: Δargmin +2.60pp, Δoverhead -0.208pp
#   feat_grayscale_score: Δargmin +2.52pp, Δoverhead -0.184pp
#   feat_chroma_complexity: Δargmin +2.30pp, Δoverhead -0.200pp
#   feat_flat_color_block_ratio: Δargmin +1.76pp, Δoverhead +0.022pp
#   feat_uniformity: Δargmin +1.18pp, Δoverhead -0.168pp
#   feat_cr_sharpness: Δargmin +0.98pp, Δoverhead +0.110pp
#   feat_cb_horiz_sharpness: Δargmin +0.84pp, Δoverhead +0.030pp
#   feat_cr_peak_sharpness: Δargmin +0.80pp, Δoverhead +0.038pp
#   feat_colourfulness: Δargmin +0.72pp, Δoverhead +0.130pp
#   feat_alpha_used_fraction: Δargmin +0.72pp, Δoverhead -0.018pp
#   feat_alpha_bimodal_score: Δargmin +0.72pp, Δoverhead -0.018pp
#   feat_cb_sharpness: Δargmin +0.70pp, Δoverhead +0.060pp

DROP_FEATURES = [
    'feat_cr_horiz_sharpness',
    'feat_laplacian_variance',
    'feat_cb_vert_sharpness',
    'feat_cb_peak_sharpness',
    'feat_edge_density',
    'feat_variance_spread',
    'feat_grayscale_score',
    'feat_chroma_complexity',
    'feat_flat_color_block_ratio',
    'feat_uniformity',
    'feat_cr_sharpness',
    'feat_cb_horiz_sharpness',
    'feat_cr_peak_sharpness',
    'feat_colourfulness',
    'feat_alpha_used_fraction',
    'feat_alpha_bimodal_score',
    'feat_cb_sharpness',
]

KEEP_FEATURES = [f for f in BASE_KEEP_FEATURES if f not in DROP_FEATURES]
