"""zenwebp picker config v3_stable — adopts the seed-stable v14+z_rmse majority winners.

The seed-stable methodology (`zentrain/tools/seed_stable_screen.py`)
runs the screen across 3 seeds and keeps only transforms that won the
majority vote, dropping features where seeds disagreed. For zenwebp's
pre-pruned KEEP_FEATURES = 33, this works:

- Original config baseline median: 20.8% argmin
- v3_stable baseline median: 48.6% argmin (Δ +27.8 pp)

Marginally better than the single-seed `zenwebp_picker_config_v2.py`
(median 45.3% argmin). Both ship; v3_stable is the safer choice.

(The 3-seed --confirm verdict is `noise` because re-screening at the
same seeds finds similar transforms; for shipping, either v2 or
v3_stable is fine.)

See `benchmarks/screen_seed_stability_findings_2026-05-17.md` for
context — the methodology works for zenwebp specifically because of
prior feature pruning; do NOT promote-and-bake v3_stable for jpeg/avif
(those have 50+ features and compound overfit).

----

Original docstring follows below:

zenwebp picker config v2 — adopts the 2026-05-17 sweep winners (seed-stable v14+z_rmse majority vote of 3 seeds).

Wraps zenwebp_picker_config + overrides FEATURE_TRANSFORMS / FEATURE_TRANSFORM_PARAMS
with the per-feature winners from the feature_transform_sweep.py
recommendation at:

  benchmarks/seed_stable_zenwebp_v14_2026-05-17/recommended_transforms.py

Generated by zentrain/tools/promote_recommended_to_config.py.
"""

from __future__ import annotations

from pathlib import Path

from zenwebp_picker_config import (  # noqa: F401
    PARETO,
    FEATURES,
    ZQ_TARGETS,
    CATEGORICAL_AXES,
    SCALAR_AXES,
    SCALAR_SENTINELS,
    SCALAR_DISPLAY_RANGES,
    FEATURE_GROUPS,
    TIME_COLUMN,
    OUTPUT_SPECS,
    SPARSE_OVERRIDES,
    parse_config_name,
    KEEP_FEATURES,
)

OUT_JSON = Path("benchmarks/zenwebp_hybrid_v3_stable_2026-05-17.json")
OUT_LOG = Path("benchmarks/zenwebp_hybrid_v3_stable_2026-05-17.log")

FEATURE_TRANSFORMS = {
    'feat_aq_map_mean': 'log',
    'feat_aq_map_p75': 'signed_cbrt',
    'feat_aq_map_std': 'winsor_then_log',
    'feat_aspect_min_over_max': 'winsor_then_log',
    'feat_cb_horiz_sharpness': 'winsor_then_log',
    'feat_cb_sharpness': 'winsor_then_log',
    'feat_chroma_complexity': 'winsor_then_log',
    'feat_colourfulness': 'clip_then_log1p_then_winsor',
    'feat_cr_horiz_sharpness': 'winsor_then_log',
    'feat_distinct_color_bins': 'signed_cbrt',
    'feat_edge_density': 'clip_then_log1p',
    'feat_edge_slope_stdev': 'signed_cbrt',
    'feat_gradient_fraction': 'winsor_then_log',
    'feat_high_freq_energy_ratio': 'winsor_then_log',
    'feat_laplacian_variance': 'signed_cbrt',
    'feat_laplacian_variance_p50': 'signed_cbrt',
    'feat_laplacian_variance_p75': 'signed_cbrt',
    'feat_laplacian_variance_p90': 'clip_then_log1p',
    'feat_max_dim': 'clip_then_log1p',
    'feat_min_dim': 'clip_then_log1p',
    'feat_noise_floor_uv': 'winsor_then_signed_cbrt',
    'feat_noise_floor_uv_p50': 'winsor_then_signed_cbrt',
    'feat_noise_floor_y_p25': 'signed_cbrt',
    'feat_noise_floor_y_p50': 'signed_cbrt',
    'feat_noise_floor_y_p75': 'signed_cbrt',
    'feat_patch_fraction': 'winsor_then_signed_cbrt',
    'feat_pixel_count': 'clip_then_log1p',
    'feat_quant_survival_uv': 'winsor_then_log',
    'feat_quant_survival_y': 'clip_then_log1p',
    'feat_quant_survival_y_p50': 'clip_then_log1p',
    'feat_quant_survival_y_p75': 'clip_then_log1p',
}

FEATURE_TRANSFORM_PARAMS = {
    'feat_aq_map_std': [0.644739, 1.24941],
    'feat_aspect_min_over_max': [0.474609, 1],
    'feat_cb_horiz_sharpness': [0.000156833, 0.058007],
    'feat_cb_sharpness': [0.000521, 0.0321315],
    'feat_chroma_complexity': [0.0139673, 0.245517],
    'feat_colourfulness': [5.04115, 0, 4.76837],
    'feat_cr_horiz_sharpness': [0.000600333, 0.254917],
    'feat_edge_density': [0.31036],
    'feat_gradient_fraction': [0.0360512, 0.713867],
    'feat_high_freq_energy_ratio': [0.0751955, 0.244223],
    'feat_laplacian_variance_p90': [4.29046],
    'feat_max_dim': [5.54518],
    'feat_min_dim': [5.2575],
    'feat_noise_floor_uv': [0, 0.139839],
    'feat_noise_floor_uv_p50': [0, 0.417598],
    'feat_patch_fraction': [0, 0.0158857],
    'feat_pixel_count': [10.7116],
    'feat_quant_survival_uv': [0.000513667, 0.0568167],
    'feat_quant_survival_y': [0.139787],
    'feat_quant_survival_y_p50': [0.132275],
    'feat_quant_survival_y_p75': [0.216931],
}
