"""zenwebp picker config pruned — drops 13 features that
the LOO multiseed analysis identified as actively harmful (removing
them improves argmin by ≥0.5 pp with overhead
trade ≤1.00 pp).

Source: benchmarks/loo_zenwebp_multiseed_2026-05-03.tsv

Generated by zentrain/tools/build_pruned_config.py.
"""

from __future__ import annotations

from pathlib import Path

from zenwebp_picker_config import (  # noqa: F401
    PARETO,
    FEATURES,
    ZQ_TARGETS,
    CATEGORICAL_AXES,
    SCALAR_AXES,
    SCALAR_SENTINELS,
    SCALAR_DISPLAY_RANGES,
    FEATURE_GROUPS,
    FEATURE_TRANSFORMS,
    TIME_COLUMN,
    OUTPUT_SPECS,
    SPARSE_OVERRIDES,
    parse_config_name,
)
from zenwebp_picker_config import KEEP_FEATURES as BASE_KEEP_FEATURES

OUT_JSON = Path("benchmarks/zenwebp_hybrid_pruned_2026-05-17.json")
OUT_LOG = Path("benchmarks/zenwebp_hybrid_pruned_2026-05-17.log")

# Drop-rationale (from LOO 2026-05-03 multiseed analysis):
#   feat_cb_sharpness: Δargmin +5.26pp, Δoverhead -0.366pp
#   feat_aq_map_std: Δargmin +5.18pp, Δoverhead -0.404pp
#   feat_high_freq_energy_ratio: Δargmin +3.14pp, Δoverhead -0.242pp
#   feat_min_dim: Δargmin +3.10pp, Δoverhead -0.042pp
#   feat_uniformity: Δargmin +2.56pp, Δoverhead -0.302pp
#   feat_cb_horiz_sharpness: Δargmin +2.44pp, Δoverhead -0.142pp
#   feat_cr_horiz_sharpness: Δargmin +2.30pp, Δoverhead -0.182pp
#   feat_aq_map_p75: Δargmin +2.08pp, Δoverhead -0.220pp
#   feat_quant_survival_y: Δargmin +1.98pp, Δoverhead -0.210pp
#   feat_quant_survival_y_p50: Δargmin +1.94pp, Δoverhead -0.160pp
#   feat_aq_map_mean: Δargmin +1.64pp, Δoverhead -0.242pp
#   feat_laplacian_variance_p75: Δargmin +1.56pp, Δoverhead -0.224pp
#   feat_distinct_color_bins: Δargmin +1.36pp, Δoverhead -0.150pp

DROP_FEATURES = [
    'feat_cb_sharpness',
    'feat_aq_map_std',
    'feat_high_freq_energy_ratio',
    'feat_min_dim',
    'feat_uniformity',
    'feat_cb_horiz_sharpness',
    'feat_cr_horiz_sharpness',
    'feat_aq_map_p75',
    'feat_quant_survival_y',
    'feat_quant_survival_y_p50',
    'feat_aq_map_mean',
    'feat_laplacian_variance_p75',
    'feat_distinct_color_bins',
]

KEEP_FEATURES = [f for f in BASE_KEEP_FEATURES if f not in DROP_FEATURES]
