#!/usr/bin/env python3
"""Build a pruned codec picker config by removing the top-N features
that hurt argmin per the existing LOO multiseed analysis.

The LOO TSV (e.g. `benchmarks/loo_zenjpeg_multiseed_2026-05-03.tsv`)
reports per-feature `mean_delta_argmin_pp` when that feature is held
out. **Positive delta = removing the feature improves the picker**.
We drop the top-N features by positive delta, with a small overhead
guard: also require `mean_delta_overhead_pp <= overhead_cap` so we
don't pick features whose removal trades argmin for bytes.

Usage:

    python3 zentrain/tools/build_pruned_config.py \\
        --loo-tsv benchmarks/loo_zenjpeg_multiseed_2026-05-03.tsv \\
        --base zenjpeg_picker_config \\
        --out zentrain/examples/zenjpeg_picker_config_pruned.py \\
        --drop-top 10 \\
        --overhead-cap 0.3
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--loo-tsv", type=Path, required=True)
    ap.add_argument("--base", required=True,
                    help="Base codec config module name (no .py)")
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--drop-top", type=int, default=10,
                    help="Number of top-positive-delta features to drop")
    ap.add_argument("--overhead-cap", type=float, default=0.3,
                    help="Max acceptable Δ overhead pp when removing a "
                    "feature (skip if removal trades argmin for bytes)")
    ap.add_argument("--min-delta-argmin", type=float, default=0.5,
                    help="Min positive delta_argmin_pp to consider for "
                    "pruning (skip near-zero deltas)")
    args = ap.parse_args()

    rows = list(csv.DictReader(open(args.loo_tsv), delimiter="\t"))
    candidates = []
    for r in rows:
        try:
            da = float(r["mean_delta_argmin_pp"])
            do = float(r["mean_delta_overhead_pp"])
        except (ValueError, KeyError):
            continue
        if da >= args.min_delta_argmin and do <= args.overhead_cap:
            candidates.append((r["feature"], da, do))
    candidates.sort(key=lambda t: t[1], reverse=True)
    to_drop = [c[0] for c in candidates[: args.drop_top]]
    if not to_drop:
        sys.exit(
            f"no features met thresholds (delta_argmin >= "
            f"{args.min_delta_argmin}, delta_overhead <= "
            f"{args.overhead_cap})"
        )

    codec_short = args.base.replace("_picker_config", "")

    # Build the dropped-features block as a literal Python list.
    drop_block = "DROP_FEATURES = [\n"
    for f in to_drop:
        drop_block += f"    {f!r},\n"
    drop_block += "]"

    summary_block = "# Drop-rationale (from LOO 2026-05-03 multiseed analysis):\n"
    for f, da, do in candidates[: args.drop_top]:
        summary_block += f"#   {f}: Δargmin {da:+.2f}pp, Δoverhead {do:+.3f}pp\n"

    # Detect what the base config actually exports — different codec
    # configs have slightly different surface (zenwebp has FEATURE_GROUPS;
    # zenjpeg / zenavif don't, etc.).
    candidate_exports = [
        "PARETO", "FEATURES",
        "ZQ_TARGETS", "CATEGORICAL_AXES", "SCALAR_AXES",
        "SCALAR_SENTINELS", "SCALAR_DISPLAY_RANGES",
        "FEATURE_GROUPS", "FEATURE_TRANSFORMS",
        "FEATURE_TRANSFORM_PARAMS",
        "TIME_COLUMN", "OUTPUT_SPECS", "SPARSE_OVERRIDES",
        "parse_config_name",
    ]
    base_path = args.out.parent / f"{args.base}.py"
    if not base_path.exists():
        sys.exit(f"base config not found: {base_path}")
    base_src = base_path.read_text()
    actually_exported = [
        name for name in candidate_exports
        if (f"\n{name} =" in base_src or f"\n{name}:" in base_src
            or f"\ndef {name}" in base_src)
    ]
    import_list = ",\n    ".join(actually_exported)

    out_text = f'''"""\
{codec_short} picker config pruned — drops {args.drop_top} features that
the LOO multiseed analysis identified as actively harmful (removing
them improves argmin by ≥{args.min_delta_argmin:.1f} pp with overhead
trade ≤{args.overhead_cap:.2f} pp).

Source: {args.loo_tsv}

Generated by zentrain/tools/build_pruned_config.py.
"""

from __future__ import annotations

from pathlib import Path

from {args.base} import (  # noqa: F401
    {import_list},
)
from {args.base} import KEEP_FEATURES as BASE_KEEP_FEATURES

OUT_JSON = Path("benchmarks/{codec_short}_hybrid_pruned_2026-05-17.json")
OUT_LOG = Path("benchmarks/{codec_short}_hybrid_pruned_2026-05-17.log")

{summary_block}
{drop_block}

KEEP_FEATURES = [f for f in BASE_KEEP_FEATURES if f not in DROP_FEATURES]
'''
    args.out.write_text(out_text)
    print(f"wrote {args.out}")
    print(f"  dropped {len(to_drop)} features:")
    for f, da, do in candidates[: args.drop_top]:
        print(f"    {f}: Δargmin {da:+.2f}pp, Δoverhead {do:+.3f}pp")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
