#!/usr/bin/env python3
"""Generate a v2 codec config that adopts the sweep's recommended transforms.

Reads a `recommended_transforms.py` (output of feature_transform_sweep.py)
and a base codec config name, emits a v2 config module that wraps the
base + overrides FEATURE_TRANSFORMS / FEATURE_TRANSFORM_PARAMS.

Usage:

    python3 zentrain/tools/promote_recommended_to_config.py \\
        --recommended benchmarks/feat_xform_zenwebp_v14_2026-05-17/recommended_transforms.py \\
        --base zenwebp_picker_config \\
        --out zentrain/examples/zenwebp_picker_config_v2.py \\
        --label "v14+z_rmse, +24.54 pp argmin (single seed)"
"""

from __future__ import annotations

import argparse
import ast
from pathlib import Path
from typing import Any


def _parse_recommended(path: Path) -> tuple[dict[str, str], dict[str, list[float]]]:
    """Read the recommended file and extract its top-level dict literals."""
    tree = ast.parse(path.read_text())
    transforms: dict[str, str] = {}
    params: dict[str, list[float]] = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 \
                and isinstance(node.targets[0], ast.Name):
            name = node.targets[0].id
            if name == "FEATURE_TRANSFORMS":
                transforms = ast.literal_eval(node.value)
            elif name == "FEATURE_TRANSFORM_PARAMS":
                params = ast.literal_eval(node.value)
    return transforms, params


def _format_dict(d: dict[str, Any], value_fmt) -> str:
    if not d:
        return "{}"
    lines = ["{"]
    for k, v in d.items():
        lines.append(f"    {k!r}: {value_fmt(v)},")
    lines.append("}")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--recommended", type=Path, required=True)
    ap.add_argument("--base", required=True,
                    help="Base codec config module name (no .py suffix)")
    ap.add_argument("--out", type=Path, required=True,
                    help="Output v2 config path")
    ap.add_argument("--label", default="",
                    help="Optional verdict label included in the docstring")
    ap.add_argument("--out-suffix", default="v2_2026-05-17",
                    help="Filename suffix for OUT_JSON / OUT_LOG paths")
    args = ap.parse_args()

    transforms, params = _parse_recommended(args.recommended)
    if not transforms:
        raise SystemExit(f"no FEATURE_TRANSFORMS dict in {args.recommended}")

    # Strip the codec prefix to derive a clean module name for the
    # OUT_JSON / OUT_LOG (e.g. zenwebp_picker_config -> zenwebp_hybrid).
    base = args.base
    codec_short = base.replace("_picker_config", "")

    # Detect SCALAR_AXES / SCALAR_SENTINELS / ... imports by trying each;
    # missing ones are skipped via the `# noqa: F401` line.
    common_exports = [
        "PARETO", "FEATURES",
        "ZQ_TARGETS", "CATEGORICAL_AXES", "SCALAR_AXES",
        "SCALAR_SENTINELS", "SCALAR_DISPLAY_RANGES",
        "FEATURE_GROUPS", "TIME_COLUMN",
        "OUTPUT_SPECS", "SPARSE_OVERRIDES",
        "parse_config_name", "KEEP_FEATURES",
    ]
    # Read the base config to verify what's exported.
    base_path = args.out.parent / f"{base}.py"
    if not base_path.exists():
        raise SystemExit(f"base config not found: {base_path}")
    base_src = base_path.read_text()
    actually_exported = [name for name in common_exports if (
        f"\n{name} =" in base_src or f"\n{name}:" in base_src
        or f"\ndef {name}" in base_src
    )]
    if "KEEP_FEATURES" not in actually_exported:
        # Always need KEEP_FEATURES.
        actually_exported.append("KEEP_FEATURES")
    import_list = ",\n    ".join(actually_exported)

    label_line = f" ({args.label})" if args.label else ""

    def fmt_str(v):
        return repr(v)

    def fmt_params(v):
        return repr(list(v))

    transforms_block = _format_dict(transforms, fmt_str)
    params_block = _format_dict(params, fmt_params)

    out_text = f'''"""\
{codec_short} picker config v2 — adopts the 2026-05-17 sweep winners{label_line}.

Wraps {base} + overrides FEATURE_TRANSFORMS / FEATURE_TRANSFORM_PARAMS
with the per-feature winners from the feature_transform_sweep.py
recommendation at:

  {args.recommended}

Generated by zentrain/tools/promote_recommended_to_config.py.
"""

from __future__ import annotations

from pathlib import Path

from {base} import (  # noqa: F401
    {import_list},
)

OUT_JSON = Path("benchmarks/{codec_short}_hybrid_{args.out_suffix}.json")
OUT_LOG = Path("benchmarks/{codec_short}_hybrid_{args.out_suffix}.log")

FEATURE_TRANSFORMS = {transforms_block}

FEATURE_TRANSFORM_PARAMS = {params_block}
'''
    args.out.write_text(out_text)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
