//! XYB 4:4:4 color round-trip **noticeability** feature
//! ([`crate::feature::AnalysisFeature::Xyb444ColorLoss`]).
//!
//! A zenjpeg JPEG can encode in BT.601 YCbCr or in libjxl-style XYB. XYB's
//! opsin → cube-root → 8-bit-sample round trip clips a sliver of warm,
//! saturated gamut (red/orange/yellow). `xyb444_color_loss` is the graded
//! perceptual magnitude of that clip: the mean **Oklab ΔE** between an
//! image's colors and what XYB's 4:4:4 (unsubsampled) round trip turns them
//! into — i.e. how *noticeably* XYB's color transform deviates from the
//! truth. High ⇒ the image lives in colors XYB reproduces less faithfully,
//! a favor-YCbCr signal for the mode picker.
//!
//! It is orthogonal to the chroma-*sharpness* family
//! ([`crate::feature::AnalysisFeature::CbHorizSharpness`] et al.): those
//! measure chroma spatial *detail* (the subsampling axis); this measures
//! gamut/saturation *clipping* in the unsubsampled transform.
//!
//! ## Why absolute (vs the original), not a vs-YCbCr differential
//!
//! YCbCr 4:4:4 is *not* lossless — its own round-trip Oklab ΔE (mean
//! ~0.0013) is comparable to XYB's (~0.0012); the two just shed in
//! different colors. So subtracting YCbCr's loss (a "vs-YCbCr delta")
//! injects YCbCr's quantization noise rather than isolating XYB's. The
//! pure **vs-original** ΔE is cleaner and predicts the RD XYB-vs-YCbCr
//! outcome better on a lean feature set (butteraugli residual +0.17 / +0.22
//! over a 4-feature curated model, vs the differential's +0.15 / +0.17 and
//! the old binary predicate's +0.06). See
//! `/mnt/v/zen/color-loss-research/accuracy_eval_2026-06-02.md` §Q–§S.
//!
//! ## Cost
//!
//! `xyb444_color_loss` is a property of the *color*: a given `(r,g,b)`
//! has a fixed XYB round-trip ΔE. The opsin+cbrt+Oklab math is therefore
//! evaluated **offline**, once, over a quantized color grid and baked into
//! a 4 KiB `.rodata` LUT ([`CONV_LOSS_DENSITY`]); each bin holds the bin's
//! mean ΔE scaled by [`reference::SCALE`] into `0..=255`. At runtime the
//! feature is a strided sample of cheap table lookups — no `cbrt`, no heap,
//! no transfer-function dependency. The exact per-color predicate and the
//! LUT regenerator live in the test module below.

// ---- runtime path: graded ΔE LUT + strided sample (no cbrt, no alloc) ----

/// Embedded XYB 4:4:4 color-round-trip noticeability LUT: 4 bits per channel
/// (16³ = 4096 bins), one byte per bin = the bin's mean Oklab ΔE between an
/// sRGB8 color and its XYB 4:4:4 round trip, scaled by [`reference::SCALE`]
/// into `0..=255` (saturating). **4 KiB of `.rodata`** — no runtime build
/// (cold start == warm cost), no allocation. Generated offline by the
/// `regenerate_density_lut` test (the exact predicate over all 16.7 M
/// colors); `lut_matches_predicate` gates that the embedded bytes still
/// match the predicate. Regenerate after any opsin / Oklab / scale change.
static CONV_LOSS_DENSITY: &[u8; 4096] = include_bytes!("conv_loss_density.bin");

/// 4-bit-per-channel bin index into [`CONV_LOSS_DENSITY`].
#[inline]
fn density_idx(r: u8, g: u8, b: u8) -> usize {
    ((r as usize >> 4) << 8) | ((g as usize >> 4) << 4) | (b as usize >> 4)
}

/// Per-image sample budget. `xyb444_color_loss` is a color statistic that
/// tolerates strided sampling; this caps per-image cost near Tier-1.
const SAMPLE_TARGET: usize = 1 << 16; // 65 536

/// Mean XYB-round-trip noticeability over a strided sample of `rgb` (a
/// tightly packed `w*h*3` sRGB8 buffer; `n = w*h` pixels). Returns the
/// scaled-and-normalized mean Oklab ΔE in `[0, 1]` — the favor-YCbCr color
/// signal. `0.0` for an empty image.
pub(crate) fn xyb444_color_loss_rgb8(rgb: &[u8], w: usize, h: usize) -> f32 {
    let n = w * h;
    debug_assert_eq!(rgb.len(), n * 3, "rgb buffer must be tightly packed w*h*3");
    if n == 0 {
        return 0.0;
    }
    let stride = (n / SAMPLE_TARGET).max(1);
    let (mut sum, mut cnt) = (0u64, 0u64);
    let mut i = 0;
    while i < n {
        let base = i * 3;
        sum += CONV_LOSS_DENSITY[density_idx(rgb[base], rgb[base + 1], rgb[base + 2])] as u64;
        cnt += 1;
        i += stride;
    }
    sum as f32 / (cnt.max(1) as f32 * 255.0)
}

// ---- runtime path: XYB-BQuarter B-channel subsample loss (J·|Δsb| B-LUT) ----

/// Embedded B-subsample LUT: 4 bits per channel (4096 bins), 3 bytes per bin —
/// `sb` (scaled-B, u8) then `J = |∂RGB/∂scaled_b|` (L1 sensitivity, LE u16). The
/// cube-root is pre-paid offline so the runtime XYB-BQuarter subsample loss is
/// `J·|Δsb|` with no transcendental. **12 KiB of `.rodata`**. Generated by the
/// `regenerate_b_lut` test; `b_lut_matches_predicate` gates that the embedded
/// bytes match the predicate.
static B_SUBSAMPLE_LUT: &[u8; 12288] = include_bytes!("b_subsample_lut.bin");

/// Read `(scaled_b, j)` for a color from [`B_SUBSAMPLE_LUT`].
#[inline]
fn b_lut_read(r: u8, g: u8, b: u8) -> (f32, f32) {
    let o = (((r as usize >> 4) << 8) | ((g as usize >> 4) << 4) | (b as usize >> 4)) * 3;
    let sb = B_SUBSAMPLE_LUT[o] as f32 / 255.0;
    let j = u16::from_le_bytes([B_SUBSAMPLE_LUT[o + 1], B_SUBSAMPLE_LUT[o + 2]]) as f32;
    (sb, j)
}

/// Mean XYB-BQuarter B-channel subsampling loss over a strided sample of 2×2
/// blocks: `J·|Δsb|`, where `Δsb` is each pixel's scaled-B deviation from its
/// 2×2 block mean and `J` is the per-color RGB sensitivity to scaled-B. High ⇒
/// the image has blue-yellow detail XYB-BQuarter's 2× B-subsample would drop —
/// a favor-XYB-Full signal. `rgb` is a tightly packed `w*h*3` sRGB8 buffer;
/// returns `0.0` for sub-2×2 images.
pub(crate) fn xyb_bquarter_chroma_loss_rgb8(rgb: &[u8], w: usize, h: usize) -> f32 {
    let (bw, bh) = (w / 2, h / 2);
    let nblocks = bw * bh;
    if nblocks == 0 {
        return 0.0;
    }
    let bstride = (nblocks / (SAMPLE_TARGET / 4)).max(1);
    let (mut xy_sum, mut samp) = (0.0f64, 0u64);
    let mut bidx = 0;
    while bidx < nblocks {
        let (bx, by) = ((bidx % bw) * 2, (bidx / bw) * 2);
        let mut sbs = [0f32; 4];
        let mut js = [0f32; 4];
        for (k, (dx, dy)) in [(0, 0), (1, 0), (0, 1), (1, 1)].into_iter().enumerate() {
            let o = ((by + dy) * w + (bx + dx)) * 3;
            let (sb, j) = b_lut_read(rgb[o], rgb[o + 1], rgb[o + 2]);
            sbs[k] = sb;
            js[k] = j;
        }
        let asb = (sbs[0] + sbs[1] + sbs[2] + sbs[3]) * 0.25;
        for k in 0..4 {
            xy_sum += (js[k] * (sbs[k] - asb).abs()) as f64;
            samp += 1;
        }
        bidx += bstride;
    }
    (xy_sum / (samp.max(1) as f64 * 3.0)) as f32
}

// ---- exact reference + LUT regenerator (test-only, f64) ------------------

#[cfg(test)]
mod reference {
    //! The exact per-color XYB-round-trip noticeability predicate the LUT is
    //! baked from, in f64 for accuracy. The XYB round trip mirrors
    //! `zenjpeg::color::xyb` exactly (same opsin matrix, scale offsets); the
    //! perceptual distance is Oklab ΔE (Björn Ottosson, 2020). Constants are
    //! duplicated from `zenjpeg/src/foundation/consts.rs` intentionally
    //! (zenanalyze does not depend on zenjpeg) and must be kept in sync.

    /// Reference ΔE → byte scale: `255 / G_REF` where `G_REF` is the p99.9 of
    /// the per-bin mean ΔE over the full color space. Fixed so the LUT is
    /// reproducible from constants alone; bins above `G_REF` saturate at 255.
    pub(crate) const G_REF: f64 = 0.001_75;
    pub(crate) const SCALE: f64 = 255.0 / G_REF;

    // --- sRGB transfer (IEC 61966-2-1), f64 ---
    fn srgb_to_linear(v: f64) -> f64 {
        if v <= 0.040_45 {
            v / 12.92
        } else {
            ((v + 0.055) / 1.055).powf(2.4)
        }
    }

    // --- sRGB8 -> scaled XYB (zenjpeg::color::xyb), through 0..1 linear ---
    const OPSIN: [f64; 9] = [
        0.30,
        0.622,
        0.078,
        0.23,
        0.692,
        0.078,
        0.243_422_69,
        0.204_767_44,
        0.551_809_87,
    ];
    const OPSIN_BIAS: f64 = 0.003_793_073_3;
    const INV_OPSIN: [f64; 9] = [
        11.031_567, -9.866_944, -0.164_623, -3.254_147, 4.418_77, -0.164_623, -3.658_851,
        2.712_923, 1.945_928,
    ];
    const SCALED_OFFSET: [f64; 3] = [0.015_386_134, 0.0, 0.277_704_59];
    const SCALED_SCALE: [f64; 3] = [22.995_788_804, 1.183_000_077, 1.502_141_333];

    pub(super) fn srgb_to_scaled_xyb(r: u8, g: u8, b: u8) -> (f64, f64, f64) {
        let lr = srgb_to_linear(r as f64 / 255.0);
        let lg = srgb_to_linear(g as f64 / 255.0);
        let lb = srgb_to_linear(b as f64 / 255.0);
        let or = (OPSIN[0] * lr + OPSIN[1] * lg + OPSIN[2] * lb + OPSIN_BIAS).max(0.0);
        let og = (OPSIN[3] * lr + OPSIN[4] * lg + OPSIN[5] * lb + OPSIN_BIAS).max(0.0);
        let ob = (OPSIN[6] * lr + OPSIN[7] * lg + OPSIN[8] * lb + OPSIN_BIAS).max(0.0);
        let nb = -OPSIN_BIAS.cbrt();
        let (cr, cg, cb) = (or.cbrt() + nb, og.cbrt() + nb, ob.cbrt() + nb);
        let x = 0.5 * (cr - cg);
        let y = 0.5 * (cr + cg);
        (
            (x + SCALED_OFFSET[0]) * SCALED_SCALE[0],
            (y + SCALED_OFFSET[1]) * SCALED_SCALE[1],
            (cb - y + SCALED_OFFSET[2]) * SCALED_SCALE[2],
        )
    }
    pub(super) fn scaled_xyb_to_srgb(sx: f64, sy: f64, sb: f64) -> (u8, u8, u8) {
        let y = sy / SCALED_SCALE[1] - SCALED_OFFSET[1];
        let x = sx / SCALED_SCALE[0] - SCALED_OFFSET[0];
        let b_xyb = sb / SCALED_SCALE[2] - SCALED_OFFSET[2] + y;
        let nb = -OPSIN_BIAS.cbrt();
        let (cr, cg, cb) = (y + x - nb, y - x - nb, b_xyb - nb);
        let cube = |v: f64| if v < 0.0 { -((-v).powi(3)) } else { v.powi(3) };
        let (or, og, ob) = (
            cube(cr) - OPSIN_BIAS,
            cube(cg) - OPSIN_BIAS,
            cube(cb) - OPSIN_BIAS,
        );
        let lr = INV_OPSIN[0] * or + INV_OPSIN[1] * og + INV_OPSIN[2] * ob;
        let lg = INV_OPSIN[3] * or + INV_OPSIN[4] * og + INV_OPSIN[5] * ob;
        let lb = INV_OPSIN[6] * or + INV_OPSIN[7] * og + INV_OPSIN[8] * ob;
        let to_u8 = |l: f64| {
            let l = l.clamp(0.0, 1.0);
            let s = if l <= 0.003_130_8 {
                l * 12.92
            } else {
                1.055 * l.powf(1.0 / 2.4) - 0.055
            };
            (s * 255.0).round() as u8
        };
        (to_u8(lr), to_u8(lg), to_u8(lb))
    }

    // --- Oklab (Ottosson 2020), from 0..1 linear sRGB ---
    fn oklab(lr: f64, lg: f64, lb: f64) -> (f64, f64, f64) {
        let l = 0.412_221_470_8 * lr + 0.536_332_536_3 * lg + 0.051_445_992_9 * lb;
        let m = 0.211_903_498_2 * lr + 0.680_699_545_1 * lg + 0.107_396_956_6 * lb;
        let s = 0.088_302_461_9 * lr + 0.281_718_837_6 * lg + 0.629_978_700_5 * lb;
        let (l_, m_, s_) = (l.cbrt(), m.cbrt(), s.cbrt());
        (
            0.210_454_255_3 * l_ + 0.793_617_785_0 * m_ - 0.004_072_046_8 * s_,
            1.977_998_495_1 * l_ - 2.428_592_205_0 * m_ + 0.450_593_709_9 * s_,
            0.025_904_037_1 * l_ + 0.782_771_766_2 * m_ - 0.808_675_766_0 * s_,
        )
    }
    fn oklab_of_srgb8(r: u8, g: u8, b: u8) -> (f64, f64, f64) {
        oklab(
            srgb_to_linear(r as f64 / 255.0),
            srgb_to_linear(g as f64 / 255.0),
            srgb_to_linear(b as f64 / 255.0),
        )
    }

    /// Oklab ΔE between a color and its XYB 4:4:4 round trip (opsin → cbrt →
    /// 8-bit-sample requant → inverse). The graded per-color noticeability
    /// the LUT bins.
    pub(crate) fn xyb_color_de(r: u8, g: u8, b: u8) -> f64 {
        let (sx, sy, sb) = srgb_to_scaled_xyb(r, g, b);
        let xq = (sx * 255.0).round() / 255.0;
        let yq = (sy * 255.0).round() / 255.0;
        let bq = (sb * 255.0).round() / 255.0;
        let (rr, gg, bb) = scaled_xyb_to_srgb(xq, yq, bq);
        let a = oklab_of_srgb8(r, g, b);
        let c = oklab_of_srgb8(rr, gg, bb);
        ((a.0 - c.0).powi(2) + (a.1 - c.1).powi(2) + (a.2 - c.2).powi(2)).sqrt()
    }

    /// Scaled byte value for one 4-bit-per-channel bin: the bin's mean
    /// [`xyb_color_de`] over its 4096 member colors, `× SCALE`, saturating.
    pub(crate) fn bin_byte(rbin: usize, gbin: usize, bbin: usize) -> u8 {
        let mut sum = 0.0f64;
        for dr in 0..16u32 {
            for dg in 0..16u32 {
                for db in 0..16u32 {
                    sum += xyb_color_de(
                        (rbin as u32 * 16 + dr) as u8,
                        (gbin as u32 * 16 + dg) as u8,
                        (bbin as u32 * 16 + db) as u8,
                    );
                }
            }
        }
        ((sum / 4096.0) * SCALE).round().clamp(0.0, 255.0) as u8
    }

    /// B-subsample LUT entry for one 4-bit bin center: `(scaled_b as u8,
    /// J as u16)` where `J = |∂RGB/∂scaled_b|` (L1, central difference). The
    /// cube-root is pre-paid here; the runtime reads these as `J·|Δsb|`.
    pub(crate) fn b_lut_bin(rbin: usize, gbin: usize, bbin: usize) -> (u8, u16) {
        const EPS: f64 = 0.05;
        let (r, g, b) = (
            (rbin * 16 + 8) as u8,
            (gbin * 16 + 8) as u8,
            (bbin * 16 + 8) as u8,
        );
        let (sx, sy, sb) = srgb_to_scaled_xyb(r, g, b);
        let lo = scaled_xyb_to_srgb(sx, sy, sb - EPS);
        let hi = scaled_xyb_to_srgb(sx, sy, sb + EPS);
        let j = ((hi.0 as i32 - lo.0 as i32).abs()
            + (hi.1 as i32 - lo.1 as i32).abs()
            + (hi.2 as i32 - lo.2 as i32).abs()) as f64
            / (2.0 * EPS);
        (
            (sb.clamp(0.0, 1.0) * 255.0).round() as u8,
            j.round().clamp(0.0, 65535.0) as u16,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn solid(r: u8, g: u8, b: u8, w: usize, h: usize) -> Vec<u8> {
        let mut v = Vec::with_capacity(w * h * 3);
        for _ in 0..w * h {
            v.extend_from_slice(&[r, g, b]);
        }
        v
    }

    /// The embedded LUT must match the exact f64 predicate it claims to bin.
    /// Full enumeration of every 7th bin's 4096 colors — strided but
    /// exhaustive (no approximation) — as a hard equality.
    #[test]
    fn lut_matches_predicate() {
        let mut checked = 0;
        for bin in (0..4096usize).step_by(7) {
            let (rb, gb, bb) = ((bin >> 8) & 15, (bin >> 4) & 15, bin & 15);
            let want = reference::bin_byte(rb, gb, bb);
            assert_eq!(
                CONV_LOSS_DENSITY[bin], want,
                "bin {bin} (R{rb} G{gb} B{bb}): embedded {} != predicate {want} — \
                 conv_loss_density.bin is stale; rerun regenerate_density_lut",
                CONV_LOSS_DENSITY[bin]
            );
            checked += 1;
        }
        assert!(checked > 500, "too few bins checked ({checked})");
    }

    /// Saturated warm gamut (where XYB's transform clips) must score above
    /// near-neutral content, and the result stays a valid `[0, 1]` fraction.
    #[test]
    fn saturated_warm_exceeds_gray() {
        let warm = xyb444_color_loss_rgb8(&solid(255, 40, 0, 32, 32), 32, 32);
        let gray = xyb444_color_loss_rgb8(&solid(128, 128, 128, 32, 32), 32, 32);
        assert!((0.0..=1.0).contains(&warm), "out of range: {warm}");
        assert!((0.0..=1.0).contains(&gray), "out of range: {gray}");
        assert!(
            warm > gray,
            "saturated warm ({warm}) should exceed gray ({gray})"
        );
    }

    /// Strided sampling is deterministic and tolerates non-square images.
    #[test]
    fn deterministic_and_nonsquare() {
        let (w, h) = (37usize, 19usize);
        let mut img = Vec::with_capacity(w * h * 3);
        for y in 0..h {
            for x in 0..w {
                if (x + y) & 1 == 0 {
                    img.extend_from_slice(&[230, 30, 10]);
                } else {
                    img.extend_from_slice(&[120, 120, 120]);
                }
            }
        }
        let a = xyb444_color_loss_rgb8(&img, w, h);
        let b = xyb444_color_loss_rgb8(&img, w, h);
        assert_eq!(a, b, "must be deterministic");
        assert!(a.is_finite() && (0.0..=1.0).contains(&a));
        assert_eq!(xyb444_color_loss_rgb8(&[], 0, 0), 0.0, "empty image → 0");
    }

    /// Regenerate `conv_loss_density.bin` from the exact predicate over all
    /// 16.7 M colors. Not a correctness gate (that's `lut_matches_predicate`);
    /// run explicitly after any opsin / Oklab / scale change:
    /// `cargo test --features experimental -p zenanalyze regenerate_density_lut -- --ignored --nocapture`
    #[test]
    #[ignore = "regeneration tool — full 16.7M-color sweep, run on demand"]
    fn regenerate_density_lut() {
        let mut lut = vec![0u8; 4096];
        for rb in 0..16 {
            for gb in 0..16 {
                for bb in 0..16 {
                    lut[(rb << 8) | (gb << 4) | bb] = reference::bin_byte(rb, gb, bb);
                }
            }
        }
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/src/conv_loss_density.bin");
        std::fs::write(path, &lut).unwrap();
        eprintln!("wrote {} bytes to {path}", lut.len());
    }

    // ---- xyb_bquarter_chroma_loss (B-subsample loss) ----

    /// The embedded B-LUT must match the exact f64 predicate (every 5th bin).
    #[test]
    fn b_lut_matches_predicate() {
        for bin in (0..4096usize).step_by(5) {
            let (rb, gb, bb) = ((bin >> 8) & 15, (bin >> 4) & 15, bin & 15);
            let (sb, j) = reference::b_lut_bin(rb, gb, bb);
            let o = bin * 3;
            assert_eq!(B_SUBSAMPLE_LUT[o], sb, "bin {bin} sb mismatch");
            assert_eq!(
                u16::from_le_bytes([B_SUBSAMPLE_LUT[o + 1], B_SUBSAMPLE_LUT[o + 2]]),
                j,
                "bin {bin} J mismatch — b_subsample_lut.bin is stale; rerun regenerate_b_lut"
            );
        }
    }

    /// B-channel spatial variation (blue/yellow checkerboard) must produce a
    /// loss above a flat gray patch; result is finite and non-negative.
    #[test]
    fn bquarter_loss_on_b_variation() {
        let (w, h) = (16usize, 16usize);
        let mut varied = vec![0u8; w * h * 3];
        let mut flat = vec![0u8; w * h * 3];
        for y in 0..h {
            for x in 0..w {
                let i = (y * w + x) * 3;
                let c = if (x + y) & 1 == 0 {
                    [20u8, 20, 230]
                } else {
                    [230, 230, 20]
                };
                varied[i..i + 3].copy_from_slice(&c);
                flat[i..i + 3].copy_from_slice(&[128, 128, 128]);
            }
        }
        let lv = xyb_bquarter_chroma_loss_rgb8(&varied, w, h);
        let lf = xyb_bquarter_chroma_loss_rgb8(&flat, w, h);
        assert!(lv > lf, "B-variation ({lv}) should exceed flat ({lf})");
        assert!(lv.is_finite() && lf >= 0.0);
        assert_eq!(xyb_bquarter_chroma_loss_rgb8(&[], 0, 0), 0.0, "empty → 0");
    }

    /// Regenerate `b_subsample_lut.bin` from the exact f64 predicate. Run after
    /// any opsin / scale change:
    /// `cargo test --features experimental -p zenanalyze regenerate_b_lut -- --ignored --nocapture`
    #[test]
    #[ignore = "regeneration tool — run on demand"]
    fn regenerate_b_lut() {
        let mut buf = Vec::with_capacity(12288);
        for rb in 0..16 {
            for gb in 0..16 {
                for bb in 0..16 {
                    let (sb, j) = reference::b_lut_bin(rb, gb, bb);
                    buf.push(sb);
                    buf.extend_from_slice(&j.to_le_bytes());
                }
            }
        }
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/src/b_subsample_lut.bin");
        std::fs::write(path, &buf).unwrap();
        eprintln!("wrote {} bytes to {path}", buf.len());
    }
}
